language: cpp
dist: bionic
compiler:
  - clang
  - gcc

install:
  - which ${CXX}
  - ${CXX} --version
  - env
  - curl -sSfO https://download.build2.org/0.12.0/build2-toolchain-0.12.0.tar.gz
  - tar xf ./build2-toolchain-0.12.0.tar.gz
  - cd build2-toolchain-0.12.0
  - sudo sh ./build.sh --local --trust yes ${CXX}

script: 
  - echo "In script!"

after_success:
  - echo "Success!"

after_failure:
  - echo "Failure!"
